spring:
  application:
    name: qr_price
  datasource: # mybatis-plus DataSource Config
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ss_price?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/ss_price?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000 # 连接超时时间，单位毫秒
      idle-timeout: 600000 # 空闲连接超时时间，单位毫秒
      max-lifetime: 1800000 # 最大连接生命周期，单位毫秒
      maximum-pool-size: 10 # 最大连接数
      minimum-idle: 5 # 最小空闲连接数
      pool-name: HikariCP-Pool # 连接池名称，便于调试
      auto-commit: true # 自动提交事务，默认为true
      connection-test-query: SELECT 1 # 测试连接的查询语句
      leak-detection-threshold: 2000 # 检测连接泄漏的时间阈值，单位毫秒
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

server:
  port: 20122
# port: 20124
#  servlet:
#    context-path: /ddinguia/web

mybatis-plus:
  type-aliases-package: com.ss.price.entity  # 使用点号分隔符
  mapper-locations: classpath:mapper/*.xml
  # 控制台打印 SQL 语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 全局配置
  global-config:
    field-strategy: NOT_EMPTY
    db-config:  # 修改为下划线连接
      # 全局逻辑删除的字段名
      logic-delete-field: is_deleted
      # 逻辑已删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0

file:
  path:
    windows: D:\Project\SensorSmart\ssprice\upload
    linux: /root/zichanliuzhuan/files/upload/
